### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by umuttopalak** [susalulmumaO12/quizz_ybot#6]
Hey I just fixed your deployment issue #5 if its not work again you should set your secrets from 
Repository > Settings > Secrets and Variables >  Actions > Add Repository Secret

**Comment by susalulmumaO12** [comment]
Hi, thank you very much, really apprecieated!

I've been having troubles with it as it's my first time working with that.

I actually tried your github actions workflow for **pythonanywhere** that I saw you mentioned on reddit, I just did not know how to work with it, but I did try to, I'll check that out!

I am also considering refactoring the code to use webhooks instead of polling, which is on branch `webhooks`.

**Comment by umuttopalak** [comment]
Hi again I see new error on action can you change file with this block and please be sure env name's are correct (apitoken - api_token for example)

```
name: Deploy pythonanywhere webapp
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Re-Deploy Pythonanywhere Django API
        uses: umuttopalak/pythonanywhere-deploy-action@v1.1.0
        with:
          host: "www.pythonanywhere.com"
          username: ${{ secrets.username }}
          api_token: ${{ secrets.api_token }}
          domain_name: ${{ secrets.domain_name }}
```
